apiVersion: v1
kind: Service
metadata:
  name: {{ include "busybox.fullname" . }}
  labels:
    {{- include "busybox.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "busybox.selectorLabels" . | nindent 4 }}
