apiVersion: v1
entries:
  common:
    - apiVersion: v2
      name: common
      version: 1.0.0
      appVersion: "null"
      description: A Helm chart for Kubernetes
      digest: 410daa910609886ed8c84fcb87cd491f232b47c5b75b6a849174e999f48f1438
      urls:
        - oci://registry-1.docker.io/kluvtad/common:1.0.0
      sources:
        - https://github.com/kluvtad/packages/tree/4727088de1ec8923904a444b6066da26fef93e5f/helm/common
    - apiVersion: v2
      name: common
      version: 1.0.1
      appVersion: "null"
      description: A Helm chart for Kubernetes
      digest: 72bdb0968c5b6afa62ae27b3ef5812d61daf763fdac529912178a7c901a35cb6
      urls:
        - oci://registry-1.docker.io/kluvtad/common:1.0.1
      sources:
        - https://github.com/kluvtad/packages/tree/0703a55a7324eda5fa7c58bf34b5530e16b08f71/helm/common
    - apiVersion: v2
      name: common
      version: 1.1.0
      appVersion: "null"
      description: A Helm chart for Kubernetes
      digest: bb0b4793b6017f37694d3fef05144f3da947fce8886d898e09fe307e74a8c42a
      urls:
        - oci://registry-1.docker.io/kluvtad/common:1.1.0
      sources:
        - https://github.com/kluvtad/packages/tree/37f5ac15d00659940c15376052d1d8bd7d0c0d7e/helm/common
    - apiVersion: v2
      name: common
      version: 1.2.0
      appVersion: "null"
      description: A Helm chart for Kubernetes
      digest: 8fa820c76ec924a740237ca6eb87f649fec5a01dcd8109297259cc9d043c4f59
      urls:
        - oci://registry-1.docker.io/kluvtad/common:1.2.0
      sources:
        - https://github.com/kluvtad/packages/tree/23e461397cc7539da2f97910f25a26ee954c6ec6/helm/common
  busybox:
    - apiVersion: v2
      name: busybox
      version: 0.1.0
      appVersion: 0.1.0
      description: A Helm chart for Kubernetes
      digest: 52d3a8b0fea4add2556f3b94c1b5d90f610ecc3c651cfa4a8605a0ff4eb32007
      urls:
        - oci://registry-1.docker.io/kluvtad/busybox:0.1.0
      sources:
        - https://github.com/kluvtad/packages/tree/aca99201aa7b7251c9f0f03c46364f00d4b326ff/helm/busybox
    - apiVersion: v2
      name: busybox
      version: 1.0.0-stable
      appVersion: 1.0.0
      description: A Helm chart for Kubernetes
      digest: 4b316b5f74655120f28fd68b05c67b09d7605d774627f10d4ab4bc04e8ba7c95
      urls:
        - oci://registry-1.docker.io/kluvtad/busybox:1.0.0-stable
      sources:
        - https://github.com/kluvtad/packages/tree/522416cc1fb9e574717055efcd202c6b698b4b2b/helm/busybox
generated: 2025-06-23T09:25:02Z
