name: Build and Push Docker Images

on:
  workflow_call:
    inputs:
      image:
        description: 'The name of the Docker image to build and push'
        required: true
        type: string
      
jobs:
  get-job-env:
    name: Get Job Environment
    runs-on: ubuntu-latest
    outputs:
      env_name: ${{ steps.set-env.outputs.env_name }}
      docker_registry: ${{ steps.set-env.outputs.docker_registry }}
      docker_username: ${{ steps.set-env.outputs.docker_username }}
      docker_password: ${{ steps.set-env.outputs.docker_password }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set Environment
        id: set-env
        run: |
          if [[ "${{ github.ref_name }}" == "main" ]]; then
            echo "env_name=production" >> $GITHUB_OUTPUT
            echo "docker_registry=ghcr.io" >> $GITHUB_OUTPUT
          else
            echo "env_name=${{ github.ref_name }}" >> $GITHUB_OUTPUT
            echo "docker_registry=${{ github.repository }}/docker" >> $GITHUB_OUTPUT
            echo "docker_username=${{ github.actor }}" >> $GITHUB_OUTPUT
            echo "docker_password=${{ secrets.GITHUB_TOKEN }}" >> $GITHUB_OUTPUT
          fi

  build-and-push:
    name: Build and Push
    runs-on: ubuntu-latest
    needs: get-job-env
    environment: 
      name: ${{ needs.get-job-env.outputs.env_name }}
    env:
      DOCKER_REGISTRY: ${{ needs.get-job-env.outputs.docker_registry }}
      DOCKER_USERNAME: ${{ needs.get-job-env.outputs.docker_username }}
      DOCKER_PASSWORD: ${{ needs.get-job-env.outputs.docker_password }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
    
      - name: Log in to Github Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Image Name and Tags
        run: |
          export SHORT_SHA=$(git rev-parse --short ${{ github.sha }})
          echo "IMAGE_NAME=${{ env.DOCKER_REGISTRY }}/${{ inputs.image }}" >> $GITHUB_ENV

          if ! [[ -f ./docker/${{ inputs.image }}/VERSION.txt ]]; then
            echo "VERSION.txt not found in ./docker/${{ inputs.image }}/"
            exit 1
          fi
          semver=$(cat ./docker/${{ inputs.image }}/VERSION.txt | tr -d '\n')

          IMAGE_TAGS=""
          if [[ "${{ github.ref_name }}" == "main" ]]; then
            IMAGE_TAGS="main|${semver}|${semver}-${SHORT_SHA}"
          else
            IMAGE_TAGS="${{ github.ref_name }}|${{ github.ref_name }}-${semver}|${{ github.ref_name }}-${semver}-${SHORT_SHA}"
          fi

          if [[ "${{ github.ref_name }}" == "main" ]]; then
            IMAGE_TAGS="${IMAGE_TAGS}|latest"
          fi
          echo "IMAGE_TAGS=${IMAGE_TAGS}" >> $GITHUB_ENV
      
      - name: Docker Args
        run: |
          DOCKER_BUILD_ARGS=""
          DOCKER_IMAGES=""
          # Docker Images
          for tag in $(echo "${{ env.IMAGE_TAGS }}" | tr '|' '\n'); do
            IMAGE="ghcr.io/${{ env.IMAGE_NAME }}:${tag}"

            DOCKER_BUILD_ARGS="${DOCKER_BUILD_ARGS} -t ${IMAGE}"
            DOCKER_IMAGES="${DOCKER_IMAGES}|${IMAGE}"
          done
          echo "DOCKER_BUILD_ARGS=${DOCKER_BUILD_ARGS}" >> $GITHUB_ENV
          echo "DOCKER_IMAGES=${DOCKER_IMAGES}" >> $GITHUB_ENV

      - name: Build Docker Image
        run: |
          docker build \
            ${{ env.DOCKER_BUILD_ARGS }} \
            ./docker/${{ inputs.image }}

      # Push the Docker image to the registry
      - name: Push Docker Image
        run: |
          for image in $(echo "${{ env.DOCKER_IMAGES }}" | tr '|' '\n'); do
            echo "Pushing ${image}"
            docker push ${image}
          done
